spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: Suman@19
  jpa:
    hibernate:
      ddl-auto: update
server:
    port: 8081
jwt:
  algorithm:
    key: hgduGWhabjh-naudhqwjanm-jhfajsnn
  issuer: Suman Maity
  expiry:
    duration: 50246698

